name: Generate Snake

on:
  schedule:
    - cron: "0 */24 * * *"  # Runs once a day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate snake animation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: devanshujangid
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
